server:
  port: ${PORT:8081}
spring:  
  application:
    name: zuul-server
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    serviceA:
      path: /gtfs-api/**
      serviceId: gtfs-service
    serviceB:
      path: /isal-api/**
      serviceId: isal-service
